import { PdfPage, renderPdf } from './pdf';
import type { PassbookSummary } from '@/types/chat';
import type { CitizenProfile } from '@/types/user';
import type { CitizenDocument } from '@/types/document';
import type { Complaint } from '@/types/complaint';
import type { TrainOption } from '@/types/train';
import { formatDate } from '@/lib/utils';

const INK: [number, number, number] = [0.09, 0.11, 0.15];
const MUTED: [number, number, number] = [0.42, 0.45, 0.5];
const ACCENT: [number, number, number] = [0.11, 0.35, 0.55];
const WARN_BG: [number, number, number] = [1, 0.96, 0.85];
const WARN_INK: [number, number, number] = [0.5, 0.33, 0.02];

interface HeaderOptions {
  title: string;
  subtitle: string;
  demoBanner: string;
}

function header(page: PdfPage, options: HeaderOptions): number {
  page.rect(0, 0, 595, 84, [0.97, 0.98, 0.99]);
  page.text('NammaSahaay', 48, 40, { size: 16, bold: true, color: ACCENT });
  page.text('One place for every service', 48, 58, { size: 9, color: MUTED });

  page.rect(48, 104, 499, 26, WARN_BG);
  page.text(options.demoBanner, 60, 121, { size: 9.5, color: WARN_INK });

  page.text(options.title, 48, 170, { size: 20, bold: true, color: INK });
  page.text(options.subtitle, 48, 190, { size: 10, color: MUTED });
  page.line(48, 206, 547, 206);
  return 234;
}

function footer(page: PdfPage, sourceName: string, sourceUrl: string) {
  page.line(48, 762, 547, 762);
  page.text('Generated by NammaSahaay AI, an independent prototype.', 48, 778, {
    size: 8,
    color: MUTED,
  });
  page.text(`Official service: ${sourceName} — ${sourceUrl}`, 48, 791, { size: 8, color: MUTED });
  page.text('Sample document. It is not issued by any government office.', 48, 804, {
    size: 8,
    color: WARN_INK,
  });
}

function row(page: PdfPage, label: string, value: string, y: number): number {
  page.text(label, 48, y, { size: 10, color: MUTED });
  page.text(value, 240, y, { size: 11, bold: true, color: INK });
  page.line(48, y + 10, 547, y + 10);
  return y + 30;
}

function wrap(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if ((current + ' ' + word).trim().length > maxChars) {
      if (current) lines.push(current.trim());
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }
  if (current) lines.push(current.trim());
  return lines;
}

function paragraph(page: PdfPage, text: string, y: number, maxChars = 88): number {
  let cursor = y;
  for (const block of text.split('\n')) {
    if (!block.trim()) {
      cursor += 8;
      continue;
    }
    for (const line of wrap(block, maxChars)) {
      page.text(line, 48, cursor, { size: 10.5, color: INK });
      cursor += 16;
    }
    cursor += 6;
  }
  return cursor;
}

export function passbookPdf(profile: CitizenProfile, passbook: PassbookSummary, entries: { period: string; employee: number; employer: number; interest: number }[]): Uint8Array {
  const page = new PdfPage();
  let y = header(page, {
    title: 'Provident Fund Passbook',
    subtitle: `Prepared for ${profile.name} on ${formatDate(new Date())}`,
    demoBanner: 'Sample copy for your reference. Not an official EPFO document.',
  });

  y = row(page, 'Member name', profile.name, y);
  y = row(page, 'UAN', passbook.uan, y);
  y = row(page, 'Member ID', passbook.memberId, y);
  y = row(page, 'Employer', passbook.employer, y);
  y = row(page, 'Statement updated', passbook.lastUpdated, y);

  y += 12;
  page.text('Summary', 48, y, { size: 13, bold: true, color: INK });
  y += 22;
  y = row(page, 'Employee contribution', `Rs. ${passbook.employeeContribution.toLocaleString('en-IN')}`, y);
  y = row(page, 'Employer contribution', `Rs. ${passbook.employerContribution.toLocaleString('en-IN')}`, y);
  y = row(page, 'Interest', `Rs. ${passbook.interest.toLocaleString('en-IN')}`, y);
  y = row(page, 'Available balance', `Rs. ${passbook.balance.toLocaleString('en-IN')}`, y);

  y += 14;
  page.text('Recent entries', 48, y, { size: 13, bold: true, color: INK });
  y += 22;
  page.text('Period', 48, y, { size: 9, color: MUTED });
  page.text('Employee', 260, y, { size: 9, color: MUTED });
  page.text('Employer', 360, y, { size: 9, color: MUTED });
  page.text('Interest', 460, y, { size: 9, color: MUTED });
  page.line(48, y + 8, 547, y + 8);
  y += 24;
  for (const entry of entries) {
    page.text(entry.period, 48, y, { size: 10, color: INK });
    page.text(`Rs. ${entry.employee.toLocaleString('en-IN')}`, 260, y, { size: 10, color: INK });
    page.text(`Rs. ${entry.employer.toLocaleString('en-IN')}`, 360, y, { size: 10, color: INK });
    page.text(`Rs. ${entry.interest.toLocaleString('en-IN')}`, 460, y, { size: 10, color: INK });
    page.line(48, y + 9, 547, y + 9);
    y += 24;
  }

  footer(page, 'Employees Provident Fund Organisation', 'https://www.epfindia.gov.in');
  return renderPdf([page]);
}

export function applicationPdf(input: {
  profile: CitizenProfile;
  title: string;
  reference: string;
  serviceName: string;
  sourceName: string;
  sourceUrl: string;
  rows: { label: string; value: string }[];
  documents: string[];
  note: string;
}): Uint8Array {
  const page = new PdfPage();
  let y = header(page, {
    title: input.title,
    subtitle: `Reference ${input.reference} — prepared on ${formatDate(new Date())}`,
    demoBanner: `Sample copy for your reference. Not an official ${input.serviceName.toLowerCase()} document.`,
  });

  y = row(page, 'Applicant', input.profile.name, y);
  y = row(page, 'City / State', `${input.profile.city}, ${input.profile.state}`, y);
  for (const item of input.rows) {
    y = row(page, item.label, item.value, y);
  }

  y += 12;
  page.text('Documents attached', 48, y, { size: 13, bold: true, color: INK });
  y += 22;
  if (input.documents.length === 0) {
    page.text('No documents attached.', 48, y, { size: 10, color: MUTED });
    y += 20;
  } else {
    for (const document of input.documents) {
      page.text(`- ${document}`, 48, y, { size: 10.5, color: INK });
      y += 18;
    }
  }

  y += 10;
  paragraph(page, input.note, y);
  footer(page, input.sourceName, input.sourceUrl);
  return renderPdf([page]);
}

export function complaintPdf(profile: CitizenProfile, complaint: Complaint): Uint8Array {
  const page = new PdfPage();
  let y = header(page, {
    title: 'Complaint Record',
    subtitle: `${complaint.reference ?? 'Draft'} — prepared on ${formatDate(new Date())}`,
    demoBanner: 'Sample copy for your reference. Not filed with any government office.',
  });

  y = row(page, 'Applicant', profile.name, y);
  y = row(page, 'Sent to', complaint.department, y);
  y = row(page, 'Category', complaint.category, y);
  y = row(page, 'Status', complaint.status.replace(/_/g, ' '), y);

  y += 12;
  page.text('Subject', 48, y, { size: 13, bold: true, color: INK });
  y += 20;
  y = paragraph(page, complaint.subject, y);

  y += 6;
  page.text('Description', 48, y, { size: 13, bold: true, color: INK });
  y += 20;
  paragraph(page, complaint.description, y);

  footer(page, complaint.officialSourceName, complaint.officialSourceUrl);
  return renderPdf([page]);
}

export function ticketPdf(input: {
  profile: CitizenProfile;
  train: TrainOption;
  date: string;
  passengers: number;
  reference: string;
}): Uint8Array {
  const page = new PdfPage();
  let y = header(page, {
    title: 'Journey Record',
    subtitle: `${input.reference} — prepared on ${formatDate(new Date())}`,
    demoBanner: 'Sample copy only. This is NOT a ticket and cannot be used to travel.',
  });

  y = row(page, 'Passenger', input.profile.name, y);
  y = row(page, 'Train', `${input.train.number} ${input.train.name}`, y);
  y = row(page, 'From', `${input.train.from} (${input.train.departure})`, y);
  y = row(page, 'To', `${input.train.to} (${input.train.arrival})`, y);
  y = row(page, 'Date', input.date, y);
  y = row(page, 'Class', input.train.travelClass, y);
  y = row(page, 'Passengers', String(input.passengers), y);
  y = row(page, 'Fare', `Rs. ${(input.train.fare * input.passengers).toLocaleString('en-IN')}`, y);

  y += 14;
  paragraph(
    page,
    'This is a sample record from a practice app. No seat is reserved, no payment was taken, and it cannot be used to travel. Book real tickets on the official IRCTC service.',
    y,
  );

  footer(page, 'IRCTC', 'https://www.irctc.co.in');
  return renderPdf([page]);
}

export function walletDocumentPdf(profile: CitizenProfile, document: CitizenDocument): Uint8Array {
  const page = new PdfPage();
  let y = header(page, {
    title: document.name,
    subtitle: `From the demo document wallet of ${profile.name}`,
    demoBanner: 'Sample copy for your reference. Not an issued document.',
  });

  y = row(page, 'Document', document.name, y);
  y = row(page, 'Category', document.category, y);
  y = row(page, 'Source', document.sourceLabel, y);
  y = row(page, 'Issued on', document.issuedOn ? formatDate(document.issuedOn) : 'Not recorded', y);
  y = row(page, 'Status', document.verification.replace(/_/g, ' '), y);
  y = row(page, 'Can be used as', document.purposes.map((p) => p.replace(/_/g, ' ')).join(', '), y);

  y += 14;
  paragraph(
    page,
    `${document.summary}\n\nThis is a sample stand-in from a practice app. It holds no real personal information and has no legal value. Get the genuine document from the office that issued it, or from your DigiLocker account.`,
    y,
  );

  footer(page, 'DigiLocker', 'https://www.digilocker.gov.in');
  return renderPdf([page]);
}
